# Pytorch

Pytorch is a widely adopted deep learning library that has the following unique feature:
<br>
It operates on a **dynamic** computational graph. 

The dynamic frameworks allows to write regular Python code, and use regular python debugging, to develop our neural network logic.

In [1]:
import torch
import numpy as np

---

# Tensors

Tensors are fundamental operational building blocks in deep learning. They are multi-dimensional matrices.

#### Types of Tensors
- 8-bit (Signed + Unsigned)
- 16-bit (Float + Int)
- 32-bit (Float + Int)
- 64-bit (Float + Int)

Let us create some basic Tensors.

In [20]:
# create a tensor
new_tensor = torch.Tensor([[1, 2], [3, 4]])
print(new_tensor)

tensor([[1., 2.],
        [3., 4.]])


An **empty tensor**, will be filled with random values

In [21]:
# create a 2 x 3 tensor with random values
empty_tensor = torch.Tensor(2, 3)
print(empty_tensor)

tensor([[ 0.0000e+00, -2.5244e-29,  8.0030e-15],
        [ 4.6577e-10,  7.9936e-15, -4.6577e-10]])


To create a tensor whose values are within a **specific range** we can use:

In [22]:
# create a 2 x 3 tensor with random values between -1and 1
uniform_tensor = torch.Tensor(2, 3).uniform_(-1, 1)
print(uniform_tensor)

# create a 2 x 3 tensor with random values from a uniform distribution on the interval [0, 1)
rand_tensor = torch.rand(2, 3)
print(rand_tensor)

# create a 2 x 3 tensor of zeros
zero_tensor = torch.zeros(2, 3)
print(zero_tensor)

tensor([[-0.8610, -0.9857, -0.3219],
        [-0.6543,  0.9118,  0.4297]])
tensor([[0.6444, 0.7462, 0.2848],
        [0.8070, 0.7104, 0.9435]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Accessing and Indexing

To access or replace elements in a tensor, we can use indexing. 
For example, `new_tensor[0][0]` will return a tensor object that contains the element at position 0, 0. 

In [25]:
# replace an element at position 0, 0
new_tensor[0][0] = 100
print(new_tensor)

tensor([[100.,   2.],
        [  3.,   4.]])


A scalar object can be also accessed via `.item()`. 

In [26]:
# access an element at position 1, 0
print(new_tensor[1][0])           # tensor([ 3.])
print(new_tensor[1][0].item())    # 3.

tensor(3.)
3.0


Slicing can also be used to access every row and column in a tensor.

In [31]:
## slicing examples
slice_tensor = torch.Tensor([[1, 2, 3], 
                             [4, 5, 6], 
                             [7, 8, 9]])

# elements from every row, first column
print(slice_tensor[:, 0])         # tensor([ 1.,  4.,  7.])

# elements from every row, last column
print(slice_tensor[:, -1])        # tensor([ 3.,  6.,  9.])

# all elements on the second row
print(slice_tensor[2, :])         # tensor([ 4.,  5.,  6.])

# all elements from first two rows
print(slice_tensor[:2, :])        # tensor([[ 1.,  2.,  3.],
                                  #         [ 4.,  5.,  6.]])

tensor([1., 4., 7.])
tensor([3., 6., 9.])
tensor([7., 8., 9.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


### Tensor Information
In order to check the type of a tensor, .type() is used. For the shape of a tensor, either .shape or .size() can be used. .dim() is for accessing the dimension of a tensor.

In [33]:
# type of a tensor
print(new_tensor.type())   # 'torch.FloatTensor'

# shape of a tensor
print(new_tensor.shape)    # torch.Size([2, 2])
print(new_tensor.size())   # torch.Size([2, 2])

# dimension of a tensor
print(new_tensor.dim())    # 2

torch.FloatTensor
torch.Size([2, 2])
torch.Size([2, 2])
2


To reshape a tensor, simply use the code .view(n,m). This will convert the shape of a tensor to the size n x m.

In [34]:
reshape_tensor = torch.Tensor([[1, 2], [3, 4]])

print(reshape_tensor.view(1,4))   # tensor([[ 1.,  2.,  3.,  4.]])

print(reshape_tensor.view(4,1))   # tensor([[ 1.],[ 2.],[ 3.],[ 4.]])

tensor([[1., 2., 3., 4.]])
tensor([[1.],
        [2.],
        [3.],
        [4.]])


### Numpy Bridge

We can convert a torch Tensor to a numpy array and vice versa easily.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

In [46]:
x = torch.ones(5)
y = x.numpy()
print(y)

[1. 1. 1. 1. 1.]


### Basic Tensor Operations

#### Transpose: `.t()` or `.permute(-1, 0)`

In [38]:
x = torch.Tensor([[1,2,3], [4,5,6]])
print(x)

# regular transpose function
print(x.t())

# transpose via permute function
print(x.permute(-1,0))

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


#### Cross Product  `a.cross(b)` or `torch.cross(a, b)`

In [40]:
tensor_1 = torch.randn(3, 3)
tensor_2 = torch.randn(3, 3)

cross_prod = tensor_1.cross(tensor_2)
print(cross_prod)

tensor([[ 0.1739, -0.7375, -0.9774],
        [ 0.0965, -0.4080,  0.2240],
        [ 0.5896,  1.2675,  0.1583]])


#### Matrix Product: `.mm()`

In [43]:
maxtrix_prod = tensor_1.mm(tensor_2)
print(maxtrix_prod)

tensor([[-0.1121, -3.6505,  1.2682],
        [ 0.4588,  1.9647,  0.1891],
        [ 0.3276, -0.1029,  0.8782]])


#### Elementwise Multiplication: `.mul()`

In [44]:
element_mult = tensor_1.mul(tensor_2)
print(element_mult)

tensor([[-0.3745, -1.2369, -0.0029],
        [-0.3203, -0.1416, -0.5198],
        [ 0.0028, -0.7180,  0.3890]])


### Using CUDA

In [51]:
x, y = torch.Tensor(2,3), torch.Tensor(2,3)
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
z = x + y
print(z)

tensor([[ 0.0000e+00, -5.0487e-29,  8.3316e-15],
        [ 3.6902e+19,  4.8250e+01,  3.9420e+12]])


---

# Autograd

The autograd package provides automatic differentiation for all operations on Tensors. It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.

## Variable

`autograd.Variable` is the central class of the package. 
It wraps a Tensor, and supports nearly all of operations defined on it. 
Once you finish your computation you can call `.backward()` and have all the gradients computed automatically.

In [88]:
from torch.autograd import Variable

y = Variable(torch.Tensor([[1.0], [-1.0], [1.0]]),  requires_grad=True)
print(y)

tensor([[ 1.],
        [-1.],
        [ 1.]], requires_grad=True)


In [95]:
loss = torch.nn.L1Loss()
target = torch.Tensor([[1.0], [1.0], [1.0]])
output = loss(y, target)
print(output)

tensor(0.6667, grad_fn=<L1LossBackward>)


In [96]:
output.backward()

In [101]:
print(output.grad_fn)

### Notes
- Gradients accumulate everytime you call them, by default, be sure to call `zero.gradient()` to avoid that

- PyTorch supports various Tensor types. Be sure to check for the types to avoid Type compatibility errors.